language: php

script:
    - composer install
    - php app/console doctrine:schema:drop --force
    - php app/console doctrine:schema:create
    - php app/console doctrine:schema:update --force
    - php app/console doctrine:fixtures:load -n
    - phpunit -c app