drop_table_library:
    resource: "@DropTableLibraryBundle/Resources/config/routing.yml"

drop_table_user:
    resource: "@DropTableUserBundle/Resources/config/routing.yml"
    prefix:   /

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    # TODO: Remove?
    prefix:   /login-with-facebook

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

facebook_login:
    pattern: /login/check-facebook

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

logout:
    path: /logout
