DropTable\UserBundle\Entity\Role:
    type: entity
    table: role
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        role:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
    manyToMany:
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: role
            inversedBy: null
            joinTable: null
            orderBy: null
    lifecycleCallbacks: {  }
