DropTable\LibraryBundle\Entity\Book:
    type: entity
    table: book
    indexes:
        fk_book_category_idx:
            columns:
                - category_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        isbn:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
        title:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        slug:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        author:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        publisher:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        description:
            type: text
            nullable: true
            length: null
            fixed: false
            comment: ''
        pages:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
        createdAt:
            type: date
            nullable: true
            comment: ''
            column: created_at
    manyToOne:
        category:
            targetEntity: Category
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                category_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
