DropTable\LibraryBundle\Entity\BookHasOwner:
    type: entity
    table: book_has_owner
    indexes:
        fk_book_has_owner_user_idx:
            columns:
                - user_id
        fk_book_has_owner_book_idx:
            columns:
                - book_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
    oneToOne:
        book:
            targetEntity: Book
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                book_id:
                    referencedColumnName: id
            orphanRemoval: false
        user:
            targetEntity: User
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                user_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
